version: "2"
services:
  postgres:
    image: debezium/postgres:13
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=password
